version: '3'

services:
  database:
    container_name: database-model
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: bridge
